services:
  database:
    image: mysql:8.4.2
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - database
    ports:
      - "8081:80"
    environment:
      - UPLOAD_LIMIT=500M
      - PMA_ARBITRARY=1

  wordpress:
    image: wordpress:6.6.2-php8.3-apache
    volumes:
      - ./logs/apache:/var/log/apache2
      - ./wp-content:/var/www/html/wp-content
    ports:
      - "8000:80"
    depends_on:
      - database
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_TABLE_PREFIX: 'MOY75_'
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME','http://localhost:8000');
        define('WP_SITEURL','http://localhost:8000');
        define('WP_CACHE', false);
        define('AUTOMATIC_UPDATER_DISABLED', true);
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', true);
        define('WP_CACHE', false);

volumes:
  db_data: {}
